# Generated by Django 5.1.7 on 2025-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_employee_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
    ]
